id = "pinescript"
name = "PineScript"
description = "PineScript support for TradingView indicators and strategies development in Zed"
authors = ["David C Cavalcante <davcavalcante@proton.me>", "Takk Innovate Studio <say@takk.ag>"]
version = "0.1.0"
schema_version = 1
repository = "https://github.com/schizoidcock/pinescript-zed"

[grammars.pinescript]
repository = "https://github.com/schizoidcock/pinescript-zed"
rev = "52a7e921f60ef8a59bbc33e3048148a0f9bfd607"
path = "tree-sitter-pinescript"
