id = "pinescript"
name = "PineScript"
description = "PineScript support for TradingView indicators and strategies development in Zed"
authors = ["David C Cavalcante <davcavalcante@proton.me>", "Takk Innovate Studio <say@takk.ag>"]
version = "0.1.0"
schema_version = 1
repository = "https://github.com/schizoidcock/pinescript-zed"

[grammars.pinescript]
repository = "https://github.com/schizoidcock/pinescript-zed"
rev = "d69b674dc4f6e6932425d4f4b806caa71a34b3b0"
path = "tree-sitter-pinescript"
